#!/bin/bash
#
# This handler sends a tick every second for n seconds when n is sent to a
# matching topic. Ticks are sent on the same topic with the last "set" component
# replaced by "tick".

# Kill concurrent run of ourselves
echo "KILL $MQTT_TOPIC" >&3

n=$1
while [ $n -ge 0 ]; do
    sleep 1
    echo -e "PUB ${MQTT_TOPIC%*set}tick 0 ${#n}\n$n" >&3
    ((n--))
done
